# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu1804"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "forwarded_port", guest: 22, host: 22022
  config.vm.network "forwarded_port", guest: 80, host: 22080
  config.vm.network "forwarded_port", guest: 443, host: 22443
  config.vm.network "forwarded_port", guest: 3306, host: 22306

  # config.vm.provision :chef_solo do |chef|  
  #   chef.arguments = "--chef-license accept"
  #   chef.add_recipe("nginx")
  #   chef.add_recipe("java")
  #   chef.add_recipe("tomcat")
  #   chef.add_recipe("mysql")
  # end

end